### PR TITLE
Refactor Some Codes

### PR DESCRIPTION
**Pull request by mohsenbostan**
some refactor to flatten code.

### CODE REVIEW

**Review by jackpit93 — CHANGES_REQUESTED** [review]
My next task was to be the refactor of this class.it's good but change `EntityScaffold` `__construct` method to :
```
public function __construct()
    {
        parent::__construct();
        $this->laravelEntityScaffold = resolve(laravelEntityScaffold::class);

    }
```
or  set to `__construct(laravelEntityScaffold $laravelEntityScaffold)`

**Comment by mohsenbostan** [comment]
> My next task was to be the refactor of this class.it's good but change `EntityScaffold` `__construct` method to :
> 
> ```
> public function __construct()
>     {
>         parent::__construct();
>         $this->laravelEntityScaffold = resolve(laravelEntityScaffold::class);
> 
>     }
> ```
> 
> or set to `__construct(laravelEntityScaffold $laravelEntityScaffold)`

Will do, I forgot to contain ioc.

**Comment by mohsenbostan** [comment]
@mohammad-najjary All changes are done.

**Comment by jackpit93** [comment]
i after run have some errors,
we don't access in info method in other class.
you should change structure and first test your code after that send PR.
thank you.

**Pull request merged**
